### ISSUE TITLE
linux FileSystemList.Get fails if /etc/mtab is not present

### ISSUE THREAD

**Issue by mwhudson** [cloudfoundry/gosigar#27]
/etc/mtab is not necessarily present, for example in a chroot, which causes test failures on Ubuntu builders: https://launchpad.net/ubuntu/+source/golang-github-cloudfoundry-gosigar/0.0~git20150402.27.3ed7c74-1/+build/9609973

I'm not sure what the function should do if the file is not there. Parse /proc/mounts instead if that is? Return an empty list?

**Comment by cppforlife** [comment]
Huh. I though I saw mounts being used.

**Comment by tianon** [comment]
Many modern distros have `/etc/mtab` as a symlink for `/proc/mounts`, so it _should_ work fine to have the code that's parsing `/etc/mtab` just fall-back directly to `/proc/mounts` if `/etc/mtab` fails (or even just switch over completely and scratch `mtab` since it should be a pretty strict subset if not an outright symlink?)
