### ISSUE TITLE
Can psnotify watch on all PIDs

### ISSUE THREAD

**Issue by markwylde** [cloudfoundry/gosigar#31]
Hi there,
This is somewhat unrelated to your main project, but regarding your psnotify sub project.
I have managed to get your code to monitor when a process forks, exec, etc. But only for a specific process/set of processes.

```
err = watcher.Watch(os.Getpid(), psnotify.PROC_EVENT_ALL)
```

This is great, but I was wondering if there was a way to watch every PID

```
err = watcher.Watch(psnotify.ALL_PID, psnotify.PROC_EVENT_ALL)
```

Or something similar?
Basically I'm looking at different ways to monitor when the operating system creates or destroys processes.

Thanks for any help you can give on this (if it's not too much to ask)

**Comment by SmilingNavern** [comment]
@markwylde have you found any solutions to this? Actually the library gets all notifications but filters them out with isWatching() func, i think it's strange default behaviour

**Comment by markwylde** [comment]
Hi @SmilingNavern Is that one of the functions in here: https://github.com/cloudfoundry/gosigar/blob/f150d34b5d03cf8a1131c4edee5def4f766c60f5/psnotify/psnotify_linux.go#L140

Unfortunately I never did find a way to watch all PIDs. This library got me so close, but as a web developer peaking into Golang it was too complicated for me.

The need for the project still remains, but I moved onto a different project. It's been a while since I looked at this, but I'm now thinking since every process is really a child of PID 1, (I think), shouldn't watching on PID 1 give all events? But I'm guess it only watched direct children, and not "grand" children (is that even the correct term?).

**Comment by SmilingNavern** [comment]
@markwylde i can try to add new function WatchAll for this project if you need this also.

Yep, if isWatching always true, then you should get all events, but there can be high memory consumption, because they track watched pids with map) 

You can't use pid 1, to watch all events, because there are many process on system at the time you want to watch this and this function doesn't check full process tree, only parent of specific process in event.
